### ISSUE TITLE
Browser breaks whenever I try to print more than 1k pages #17

### ISSUE THREAD

**Issue by aliraza9996** [GrapeCity/activereportsjs-samples#1]
So here is a drawback of using Active Reports JS in React.
I am retrieving all my data form the backend and when I click generate report on the front-end, the data appears to be accurate and whenever active report's export function is called, (I am not using a preview, I am directly exporting through code), the page becomes unresponsive and that behaves different on all computers since its highly dependent on the available RAM.
I am not able to go to thousands of users and change RAM settings.
I think there should be another way around in the next release ASAP to tackle these performance issues.

**Comment by sAbakumoff** [comment]
Hello,
Please send this query via the support channel at https://www.grapecity.com/support
